// Generated by gencpp from file tiago_controller/move.msg
// DO NOT EDIT!


#ifndef TIAGO_CONTROLLER_MESSAGE_MOVE_H
#define TIAGO_CONTROLLER_MESSAGE_MOVE_H

#include <ros/service_traits.h>


#include <tiago_controller/moveRequest.h>
#include <tiago_controller/moveResponse.h>


namespace tiago_controller
{

struct move
{

typedef moveRequest Request;
typedef moveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move
} // namespace tiago_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tiago_controller::move > {
  static const char* value()
  {
    return "bd8ad08e16c09384d95325007ea8433d";
  }

  static const char* value(const ::tiago_controller::move&) { return value(); }
};

template<>
struct DataType< ::tiago_controller::move > {
  static const char* value()
  {
    return "tiago_controller/move";
  }

  static const char* value(const ::tiago_controller::move&) { return value(); }
};


// service_traits::MD5Sum< ::tiago_controller::moveRequest> should match
// service_traits::MD5Sum< ::tiago_controller::move >
template<>
struct MD5Sum< ::tiago_controller::moveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tiago_controller::move >::value();
  }
  static const char* value(const ::tiago_controller::moveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago_controller::moveRequest> should match
// service_traits::DataType< ::tiago_controller::move >
template<>
struct DataType< ::tiago_controller::moveRequest>
{
  static const char* value()
  {
    return DataType< ::tiago_controller::move >::value();
  }
  static const char* value(const ::tiago_controller::moveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tiago_controller::moveResponse> should match
// service_traits::MD5Sum< ::tiago_controller::move >
template<>
struct MD5Sum< ::tiago_controller::moveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tiago_controller::move >::value();
  }
  static const char* value(const ::tiago_controller::moveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago_controller::moveResponse> should match
// service_traits::DataType< ::tiago_controller::move >
template<>
struct DataType< ::tiago_controller::moveResponse>
{
  static const char* value()
  {
    return DataType< ::tiago_controller::move >::value();
  }
  static const char* value(const ::tiago_controller::moveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TIAGO_CONTROLLER_MESSAGE_MOVE_H
